name: Audit organization security posture
on:
  schedule:
    - cron: "30 0 * * 1-5"
  workflow_dispatch:

permissions: read-all

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to publish results and get a badge (see publish_results below).
      id-token: write
    steps:
      - name: Legitify Analyze
        uses: Legit-Labs/legitify@main
        with:
          legitify_base_version: main
          compile_legitify: true
          github_token: ${{ secrets.PAT_FOR_LEGITIFY }}
          ignore-policies: |
            code_review_not_required
            code_review_by_two_members_not_required
            code_review_not_limited_to_code_owners
            non_linear_history
            no_conversation_resolution
            no_signed_commits
            review_dismissal_allowed
            pushes_are_not_restricted
            vulnerability_alerts_not_enabled
            ghas_dependency_review_not_enabled
            scorecard_score_too_low
            token_default_permissions_is_read_write
            actions_can_approve_pull_requests
            users_allowed_to_bypass_ruleset
            repository_secret_is_stale
            secret_scanning_not_enabled
